import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={'/'}> Home</Link>
      <Link href={'/about'}> About</Link>
      <Link href={'/blog'}> Blog</Link>
    </div>
  )
}

export default Home
